In [1]:
import pandas as pd

In [2]:
#dummies
df = pd.read_csv('homeprices.csv')
df

        town  area   price
0    panipat  2600  550000
1    panipat  3000  565000
2    panipat  3200  610000
3    panipat  3600  680000
4    panipat  4000  725000
5   dehradun  2600  585000
6   dehradun  2800  615000
7   dehradun  3300  650000
8      delhi  3600  710000
9      delhi  2600  575000
10     delhi  2900  600000
11     delhi  3100  620000
12     delhi  3600  695000

In [4]:
dummies = pd.get_dummies(df.town)
dummies

    dehradun  delhi  panipat
0      False  False     True
1      False  False     True
2      False  False     True
3      False  False     True
4      False  False     True
5       True  False    False
6       True  False    False
7       True  False    False
8      False   True    False
9      False   True    False
10     False   True    False
11     False   True    False
12     False   True    False

In [8]:
df_dummies = pd.concat([df, dummies],axis='columns')
df_dummies

        town  area   price  dehradun  delhi  panipat
0    panipat  2600  550000     False  False     True
1    panipat  3000  565000     False  False     True
2    panipat  3200  610000     False  False     True
3    panipat  3600  680000     False  False     True
4    panipat  4000  725000     False  False     True
5   dehradun  2600  585000      True  False    False
6   dehradun  2800  615000      True  False    False
7   dehradun  3300  650000      True  False    False
8      delhi  3600  710000     False   True    False
9      delhi  2600  575000     False   True    False
10     delhi  2900  600000     False   True    False
11     delhi  3100  620000     False   True    False
12     delhi  3600  695000     False   True    False

In [9]:
df_dummies.drop(['town','delhi'],axis='columns',inplace=True)
df_dummies

    area   price  dehradun  panipat
0   2600  550000     False     True
1   3000  565000     False     True
2   3200  610000     False     True
3   3600  680000     False     True
4   4000  725000     False     True
5   2600  585000      True    False
6   2800  615000      True    False
7   3300  650000      True    False
8   3600  710000     False    False
9   2600  575000     False    False
10  2900  600000     False    False
11  3100  620000     False    False
12  3600  695000     False    False

In [11]:
df_dummies.replace([True,False],[1,0], inplace=True)
df_dummies

C:\Users\HP\AppData\Local\Temp\ipykernel_17772\1272669713.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_dummies.replace([True,False],[1,0], inplace=True)

    area   price  dehradun  panipat
0   2600  550000         0        1
1   3000  565000         0        1
2   3200  610000         0        1
3   3600  680000         0        1
4   4000  725000         0        1
5   2600  585000         1        0
6   2800  615000         1        0
7   3300  650000         1        0
8   3600  710000         0        0
9   2600  575000         0        0
10  2900  600000         0        0
11  3100  620000         0        0
12  3600  695000         0        0

In [12]:
x = df_dummies.drop('price',axis='columns')
x

    area  dehradun  panipat
0   2600         0        1
1   3000         0        1
2   3200         0        1
3   3600         0        1
4   4000         0        1
5   2600         1        0
6   2800         1        0
7   3300         1        0
8   3600         0        0
9   2600         0        0
10  2900         0        0
11  3100         0        0
12  3600         0        0

In [13]:
y = df_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [17]:
model.predict([[2600,0,1]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([538032.72727274])

In [18]:
model.predict([[2600,1,0]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([577857.57575759])